readium/kotlin-toolkit

- CHANGELOG.md
- readium/navigator/src/main/java/org/readium/r2/navigator/epub/EpubNavigatorFragment.kt
- readium/navigator/src/main/java/org/readium/r2/navigator/pager/R2EpubPageFragment.kt
- readium/navigator/src/main/java/org/readium/r2/navigator/pager/R2FXLPageFragment.kt
* `EpubNavigatorFragment`'s `goForward()` and `goBackward()` are now jumping to the previous or next pages instead of resources.
The implementation was not following the spec of `Navigator`, since it was jumping between resources instead of pages.
```kotlin
/**
* Moves to the next content portion (eg. page) in the reading progression direction.
*/
fun goForward(animated: Boolean = false, completion: () -> Unit = {}): Boolean
/**
* Moves to the previous content portion (eg. page) in the reading progression direction.
*/
fun goBackward(animated: Boolean = false, completion: () -> Unit = {}): Boolean
```
I also made the conformance to `R2BasicWebView.Listener` private in `EpubNavigatorFragment`, to avoid future conflicts.
> Fix EpubNavigatorFragment.goBackward/Forward()

- readium/shared/src/main/java/org/readium/r2/shared/util/http/HttpException.kt
- readium/shared/src/main/java/org/readium/r2/shared/util/http/ProblemDetails.kt
- readium/shared/src/main/java/org/readium/r2/shared/util/mediatype/MediaType.kt
- readium/shared/src/main/java/org/readium/r2/shared/util/mediatype/Sniffer.kt
- readium/shared/src/test/java/org/readium/r2/shared/util/mediatype/SnifferTest.kt
When provided with a JSON document content, the JSON media type was taking precedence during sniffing.
Note that this problem could impact any media type based on JSON if there's no explicit sniffer. For example:
```kotlin
MediaType.ofBytes({ "{}".toByteArray() }, mediaType = "application/whatnot+json"))
```
This will return `application/json` instead of `application/whatnot+json`, because the media type is not known but we can detect a JSON document from the bytes content. Maybe we need a different strategy, for example only returning `application/json` if the media type is more generic (e.g. `application/octet-stream` or `text/plain`).
> Fix sniffing a JSON Problem Details media type

- readium/shared/src/main/java/org/readium/r2/shared/util/mediatype/SnifferContent.kt
- readium/streamer/src/main/java/org/readium/r2/streamer/parser/pdf/PdfiumDocument.kt
We got some crash reports caused by Out of Memory error when rendering a PDF cover.
> Fix OutOfMemory crash when rendering a PDF cover

- readium/shared/src/main/java/org/readium/r2/shared/extensions/ContentResolver.kt
Seems like `ContentResolver.query()` can throw exceptions, we got some weird reports in production:
> Catch exceptions thrown in ContentResolver.queryProjection()

- test-app/src/main/java/org/readium/r2/testapp/outline/NavigationFragment.kt
- test-app/src/main/java/org/readium/r2/testapp/outline/OutlineFragment.kt
- test-app/src/main/java/org/readium/r2/testapp/reader/ReaderActivity.kt
- test-app/src/main/java/org/readium/r2/testapp/utils/SystemUiManagement.kt
- test-app/src/main/res/layout/fragment_outline.xml
- test-app/src/main/res/layout/fragment_screen_reader.xml
This PR fixes a few lingering UI bugs that have plagued the testapp for a bit now.
1. The Outline fragment (ToC, bookmarks, etc) now has a back button in the toolbar that returns to the reader screen without changing the page
2. The height of the toolbar is no longer being used to pad the UI.  For screens that need that padding because the contents are underneath the toolbar, `android:layout_marginTop="?attr/actionBarSize"` should be added to the root element
3. When the insets were being applied, it was using `statusBars` instead of `systemBars` and caused the TTS screen to not render the control buttons properly.  Think I caused that one.
4. The control buttons on the TTS screen resized to 48dp x 48dp
5. I also added a divider item decoration to the table of contents view, I think it …
> Fix lingering UI bugs

- build.gradle
- readium/lcp/build.gradle
- readium/navigator/build.gradle
- readium/opds/build.gradle
- readium/shared/build.gradle
- readium/streamer/build.gradle
Allow to publish sources and documentation to Maven. I checked this can be used  by hand, and I _think_ it will be usable with Jitpack as well. It would make debugging much easier in apps using Jitpack.
> Enable source and doc publishing

- CHANGELOG.md
- readium/navigator/src/main/java/org/readium/r2/navigator/util/EdgeTapNavigation.kt
- test-app/src/main/java/org/readium/r2/testapp/reader/EpubReaderFragment.kt
- test-app/src/main/java/org/readium/r2/testapp/reader/ImageReaderFragment.kt
- test-app/src/main/java/org/readium/r2/testapp/reader/PdfReaderFragment.kt
- test-app/src/main/java/org/readium/r2/testapp/reader/VisualReaderFragment.kt
* A new convenience utility `EdgeTapNavigation` to trigger page turns while tapping the screen edges.
* It takes into account the navigator reading progression to move into the right direction.
* Call it from the `VisualNavigator.Listener.onTap()` callback as demonstrated below:
```kotlin
override fun onTap(point: PointF): Boolean {
val navigated = edgeTapNavigation.onTap(point, requireView())
if (!navigated) {
// Fallback action, for example toggling the app bar.
}
return true
}
```
---
This utility is useful for two reasons:
* We want to let the apps have total control over the tap events, and decide whether or not to handle page turns with edge taps.
* Implementing the edge taps properly (taking into account the reading progression) is not so easy.
> Add `EdgeTapNavigation` to trigger page turns on edge taps

- CHANGELOG.md
- readium/navigator/src/main/java/org/readium/r2/navigator/epub/EpubNavigatorFragment.kt
- test-app/src/main/java/org/readium/r2/testapp/reader/ReaderActivity.kt
* EPUB: Fallback on `reflowable` if the `presentation.layout` hint is missing from a manifest.
Slack discussion for reference: https://readium.slack.com/archives/C703MSTQU/p1636725222048800?thread_ts=1636469403.043000&cid=C703MSTQU
> Navigator: Fix EPUB layout fallback

- .idea/codeStyles/Project.xml
- .idea/codeStyles/codeStyleConfig.xml
- CHANGELOG.md
- readium/lcp/src/main/java/org/readium/r2/lcp/license/LicenseValidation.kt
- readium/shared/src/test/java/org/readium/r2/shared/fetcher/ArchiveFetcherTest.kt
- test-app/src/main/java/org/readium/r2/testapp/reader/BaseReaderFragment.kt
* Fix building with Kotlin 1.6.
---
This doesn't bump the minimum required Kotlin version to 1.6, but fixes any build issue if someone chooses to use it.
> Fix building with Kotlin 1.6

- CHANGELOG.md
- readium/navigator/src/main/java/org/readium/r2/navigator/Navigator.kt
- readium/navigator/src/main/java/org/readium/r2/navigator/epub/EpubNavigatorFragment.kt
- readium/navigator/src/main/java/org/readium/r2/navigator/image/ImageNavigatorFragment.kt
- readium/navigator/src/main/java/org/readium/r2/navigator/media/MediaSessionNavigator.kt
- readium/navigator/src/main/java/org/readium/r2/navigator/pdf/PdfNavigatorFragment.kt
* The new `Navigator.Listener.onJumpToLocator()` API is called every time the navigator jumps to an explicit location, which might break the linear reading progression.
* For example, it is called when clicking on internal links or programmatically calling `Navigator.go()`, but not when turning pages.
* You can use this callback to implement a navigation history by differentiating between continuous and discontinuous moves.
---
Note: This is a quickfix for the shortcomings of the current Navigator API which can't be used to build a navigation history. In the [future navigator](https://github.com/readium/kotlin-toolkit/discussions/51) I think we should emit more information about a navigation event, such as the source (link clicked, `go()` call, page turned, skip forward, etc.).
> Add API `Navigator.Listener.onJumpToLocator()`

- CHANGELOG.md
- readium/navigator/src/main/java/org/readium/r2/navigator/epub/EpubNavigatorFragment.kt
* EPUB: Offset of the current selection's `rect` to take into account the vertical padding.
> EPUB Navigator: Fix the rect of the current selection

- gradle/libs.versions.toml2
This does not impact any functionality, it's an update to the toml file for potential future use of it for dependency and version management.
> Add more libraries to toml file

- CHANGELOG.md
- readium/streamer/src/main/java/org/readium/r2/streamer/fetcher/HtmlInjector.kt
- readium/streamer/src/test/java/org/readium/r2/streamer/fetcher/HtmlInjectorTest.kt
* [#193](https://github.com/readium/r2-navigator-kotlin/issues/193) Fixed invisible `<audio>` elements.
> Fix invisible `<audio>` elements

- CHANGELOG.md
- readium/streamer/src/main/java/org/readium/r2/streamer/parser/epub/EpubDeobfuscator.kt
- readium/streamer/src/test/java/org/readium/r2/streamer/parser/epub/EpubDeobfuscatorTest.kt
* Fixed reading ranges of obfuscated EPUB resources.
(Kudos to @chocolatkey who spotted this)
> Fix reading ranges of obfuscated EPUB resources

- CHANGELOG.md
- readium/navigator-media2/src/main/java/org/readium/navigator/media2/MediaNavigator.kt
- readium/navigator/src/main/java/org/readium/r2/navigator/audiobook/R2AudiobookActivity.kt
- readium/navigator/src/main/java/org/readium/r2/navigator/epub/EpubNavigatorFragment.kt
- readium/navigator/src/main/java/org/readium/r2/navigator/image/ImageNavigatorFragment.kt
- readium/navigator/src/main/java/org/readium/r2/navigator/media/MediaService.kt
- readium/navigator/src/main/java/org/readium/r2/navigator/media/MediaSessionNavigator.kt
- readium/navigator/src/main/java/org/readium/r2/navigator/pdf/PdfNavigatorFragment.kt
- readium/shared/src/main/java/org/readium/r2/shared/publication/Locator.kt
- readium/shared/src/main/java/org/readium/r2/shared/publication/Manifest.kt
- readium/shared/src/main/java/org/readium/r2/shared/publication/Publication.kt
- readium/shared/src/main/java/org/readium/r2/shared/publication/services/search/StringSearchService.kt
- readium/shared/src/test/java/org/readium/r2/shared/publication/LocatorTest.kt
- readium/shared/src/test/java/org/readium/r2/shared/publication/ManifestTest.kt
- readium/shared/src/test/java/org/readium/r2/shared/publication/PublicationTest.kt
- test-app/src/main/java/org/readium/r2/testapp/outline/NavigationFragment.kt
- test-app/src/main/java/org/readium/r2/testapp/tts/ScreenReaderEngine.kt
* `Link.toLocator()` is deprecated as it may create an incorrect `Locator` if the link `type` is missing.
* Use `publication.locatorFromLink()` instead.
---
See Slack discussion for context: https://readium.slack.com/archives/C703MSTQU/p1642520174001200
> Deprecate `Link.toLocator()` in favor of `Publication.locatorFromLink()`

- build.gradle.kts
- settings.gradle.kts
While integrating the latest Kotlin toolkit using the Gradle Kotlin DSL as a Git submodule, I faced this error:
According to [this Gradle forum post](https://discuss.gradle.org/t/error-plugin-already-on-the-classpath-must-not-include-a-version/31814/5), we can fix this by moving the version management to `settings.gradle.kts` instead.
Some additional info from the official documentation: https://docs.gradle.org/current/userguide/plugins.html#sec:plugin_version_management
> Move the Gradle plugins versions into `settings.gradle.kts`

- readium/navigator/src/main/java/org/readium/r2/navigator/media/MediaService.kt
- readium/shared/src/main/java/org/readium/r2/shared/FuelPromiseExtension.kt
Fix #92
Solution found in https://stackoverflow.com/a/47654126
> Use `startForegroundService()` for the `MediaService`

- readium/shared/src/main/java/org/readium/r2/shared/util/http/DefaultHttpClient.kt
- readium/shared/src/main/java/org/readium/r2/shared/util/http/HttpClient.kt
This is useful to get access to the original request HTTP headers or the `extras` bundle.
I used this in the context of [Authentication for OPDS](https://drafts.opds.io/authentication-for-opds-1.0.html), to retrieve the Authentication Document identifier from the request's `extras`.
Twin Swift PR: https://github.com/readium/swift-toolkit/pull/31
> Associate the `HttpResponse` with the source `HttpRequest`

- CHANGELOG.md
- readium/navigator/src/main/java/org/readium/r2/navigator/R2BasicWebView.kt
- readium/navigator/src/main/java/org/readium/r2/navigator/epub/EpubNavigatorFragment.kt
- readium/navigator/src/main/java/org/readium/r2/navigator/pager/R2EpubPageFragment.kt
- readium/navigator/src/main/java/org/readium/r2/navigator/pager/R2FXLPageFragment.kt
We have a situation where:
1. we embed the navigator (not full screen)
2. our host activity already handles insets and we want it to keep using LAYOUT_IN_DISPLAY_CUTOUT_MODE_SHORT_EDGES
In this scenario we want to avoid additional padding applied for insets within the reader.
> Allow to disable display cutouts padding

- CHANGELOG.md
- readium/navigator/src/main/java/org/readium/r2/navigator/epub/EpubNavigatorFragment.kt
- readium/shared/src/main/java/org/readium/r2/shared/publication/Locator.kt
- readium/shared/src/test/java/org/readium/r2/shared/publication/LocatorTest.kt
- test-app/src/main/java/org/readium/r2/testapp/bookshelf/BookRepository.kt
- test-app/src/main/java/org/readium/r2/testapp/db/BooksDao.kt
- test-app/src/main/java/org/readium/r2/testapp/outline/BookmarksFragment.kt
- test-app/src/main/java/org/readium/r2/testapp/outline/HighlightsFragment.kt
- test-app/src/main/java/org/readium/r2/testapp/outline/NavigationFragment.kt
* Fix #93 
The EPUB `currentLocator` was not updated if the `publication.positions` was missing, which is the case by default for WebPubs.
Also added a `Locator.Builder` object to simplify progressively constructing a `Locator`.
> Fix EPUB `currentLocator` update when `positions` are missing

- build.gradle.kts
- gradle/wrapper/gradle-wrapper.properties
- readium/lcp/build.gradle.kts
- readium/navigator-media2/build.gradle.kts
- readium/navigator/build.gradle.kts
- readium/navigator/src/main/java/org/readium/r2/navigator/R2BasicWebView.kt
- readium/opds/build.gradle.kts
- readium/shared/build.gradle.kts
- readium/streamer/build.gradle.kts
- settings.gradle.kts
- test-app/build.gradle.kts
EDIT: The following is outdated, I forgot about this other issue:
* https://github.com/readium/kotlin-toolkit/pull/97
---
I moved the Gradle plugin versions from the [`settings.gradle.kts`'s `pluginManagement` section](https://docs.gradle.org/current/userguide/plugins.html#sec:plugin_version_management) to the [root `build.gradle.kts` file](https://developer.android.com/studio/releases/gradle-plugin#updating-plugin) instead. The [AGP Upgrade Assistant](https://developer.android.com/studio/build/agp-upgrade-assistant) was not working with `settings.gradle.kts` and having the versions in the root `build.gradle.kts` seems to be enough:
>You can specify the plugin version in either the File > Project Structure > Project menu in Android Studio, or the top-level build.gradle file. The plugin …
> Upgrade dependencies and Gradle

- .gitignore
- build.gradle.kts
- mkdocs.yml
On the documentation website, code blocks are not being highlighted.  This PR fixes that by uncommenting the `markdown_extensions` in `mkdocs.yml`.  In addition, I also added the `site/` directory to gitignore and to the `cleanDocs` gradle script, and changed the copyright year for mkdocs to 2022.
> Fix code highlighting in docs

- CHANGELOG.md
- readium/navigator/src/main/java/org/readium/r2/navigator/epub/EpubNavigatorFragment.kt
- readium/navigator/src/main/java/org/readium/r2/navigator/pager/R2EpubPageFragment.kt
* Fixed emitting `currentLocator` with fixed layout EPUBs.
* Prevent refreshing an already loaded EPUB resource when jumping to a `Locator` in it.
> Navigator: Fix `currentLocator` with FXL and prevent unnecessary refreshes 

- test-app/src/main/java/org/readium/r2/testapp/catalogs/CatalogFeedListFragment.kt
They now require a paid donation to access their catalog.
> Remove the standardebooks.org OPDS catalog

- readium/lcp/src/main/java/org/readium/r2/lcp/license/License.kt
- readium/lcp/src/main/java/org/readium/r2/lcp/license/LicenseValidation.kt
- readium/lcp/src/main/java/org/readium/r2/lcp/service/NetworkService.kt
I added an `Accept` header on status document request, since some servers requires this header to accept this request.
`Accept` is now set to `application/json` since it's a json document.
> Licenses : Add Accept header on fetch status document request

- CHANGELOG.md
- readium/shared/src/main/java/org/readium/r2/shared/util/http/DefaultHttpClient.kt
* Add support for unsafe HTTP redirections with `HttpDefaultClient`.
* You will need to opt-in explicitly by implementing `HttpDefaultClient.Callback.onFollowUnsafeRedirect`.
We had a concrete case when working with the OPDS catalog from the BNF. It contains HTTP links like:
```
http://gallica.bnf.fr/ark:/12148/bpt6k6559996k.epub
```
which redirects to the HTTPS
```
https://gallica.bnf.fr/ark:/12148/bpt6k6559996k.epub
```
This failed with `HttpURLConnection` because of the scheme change.
For more information on why it's not possible by default https://stackoverflow.com/a/26046079
This PR adds a way to opt-in for explicit redirections in this case. Apps will need to opt-in as it could be unsafe for example with a `POST` or if the domain changes.
> Support for unsafe HTTP redirections with `HttpDefaultClient`

- readium/navigator/src/main/java/org/readium/r2/navigator/R2BasicWebView.kt
- readium/navigator/src/main/java/org/readium/r2/navigator/epub/EpubNavigatorFragment.kt
- readium/navigator/src/main/java/org/readium/r2/navigator/epub/EpubNavigatorViewModel.kt
- readium/navigator/src/main/res/layout/popup_footnote.xml
- test-app/src/main/res/values/styles.xml
* Fix a regression in the new (lack of) EPUB server when showing footnotes. The HTML content couldn't be fetched by `JSoup` of course.
* Fix the pop-up background color when the dark theme is enabled.
* Follow the system dark theme in the test app.
> Fix EPUB footnotes pop-up

- CHANGELOG.md
- readium/navigator/src/main/java/org/readium/r2/navigator/pager/R2FXLPageFragment.kt
* [#76](https://github.com/readium/kotlin-toolkit/issues/76) Fixed EPUB fixed layout font size affected by device settings.
---
* Fix #76
> Fix FXL font size affected by device settings

- test-app/src/main/java/org/readium/r2/testapp/catalogs/PublicationDetailFragment.kt
- test-app/src/main/res/menu/bottom_nav_menu.xml
- test-app/src/main/res/navigation/about.xml
- test-app/src/main/res/navigation/bookshelf.xml
- test-app/src/main/res/navigation/catalogs.xml
- test-app/src/main/res/navigation/navigation.xml
This PR fixes two relatively small issues with the testapp.
1. When a publication doesn't have a cover image (in the `images` array in the OPDS feed), the publication detail screen crashes.  Added a check to make sure it has an image before trying to load it
2. Under the scenario outlined below, the bottom navigation selected tab would break.  This was reproduced in a minimal repo.  The fix was to add separate nav graphs for each of the tabs, in addition to the main one.  Borrowed from https://github.com/android/architecture-components-samples/tree/master/NavigationAdvancedSample/app/src/main/res/navigation
Selected Tab Issue
1. Select the Catalogs tab
2. Select a feed to go to the catalog screen
3. Select the Bookshelf tab
4. Select the Catalogs tab
Result:  It navigates to the catalog …
> Fix bottom tabs and publication detail in testapp

- CHANGELOG.md
- readium/streamer/build.gradle.kts
- test-app/build.gradle.kts
* [#286](https://github.com/readium/kotlin-toolkit/issues/286) Fixed broken dependency to NanoHTTPD.
---
Original fix by @stevenzeck from https://github.com/readium/kotlin-toolkit/pull/287
> Fix broken dependency to NanoHTTPD

- .github/workflows/docs.yml
- mkdocs.yml
- settings.gradle.kts
- Addresses a formatting issue in mkdocs.yml file that prevented the `mike` command from running
- Added missing index files for media2, PDFium, and Pspdfkit under "Adapters", which is also under "API Reference". Unsure of case sensitivity for PDFium and Pspdfkit, so feel free to correct
- Updated the docs workflow to copy the README.md from the root project into the docs folder and replace the index.md file that is generated by Dokka. The one from Dokka is just links to the APIs, which we have in the left nav anyways
> Fix documentation config errors and use README

- README.md
- build.gradle.kts
- readium/adapters/pdfium/build.gradle.kts
- readium/adapters/pdfium/pdfium-document/build.gradle.kts
- readium/adapters/pdfium/pdfium-navigator/build.gradle.kts
- readium/adapters/pspdfkit/build.gradle.kts
- readium/adapters/pspdfkit/pspdfkit-document/build.gradle.kts
- readium/adapters/pspdfkit/pspdfkit-navigator/build.gradle.kts
- readium/lcp/build.gradle.kts
- readium/navigator-media2/build.gradle.kts
- readium/navigator/build.gradle.kts
- readium/navigator/src/main/java/org/readium/r2/navigator/media/ExoMediaPlayer.kt
- readium/opds/build.gradle.kts
- readium/streamer/build.gradle.kts
- settings.gradle.kts
- test-app/build.gradle.kts
Recommend to use a [Gradle Composite build](https://docs.gradle.org/current/userguide/composite_builds.html) to integrate the Readium toolkit as a local clone. This simplifies significantly the setup in the host app.
I decided to use the same group and artifact IDs as JitPack. This allows an app to write:
```
implementation 'com.github.readium.kotlin-toolkit:readium-shared'
```
to reference the official JitPack binaries. Then, just by adding `includeBuild 'readium'`, it will switch to a local submodule.
> Fix integration as Git submodule

- CHANGELOG.md
- readium/navigator/src/main/java/org/readium/r2/navigator/epub/css/ReadiumCss.kt
- readium/navigator/src/test/java/org/readium/r2/navigator/epub/css/ReadiumCssTest.kt
- readium/streamer/src/main/java/org/readium/r2/streamer/fetcher/HtmlInjector.kt
- readium/streamer/src/test/java/org/readium/r2/streamer/fetcher/HtmlInjectorTest.kt
* [#292](https://github.com/readium/kotlin-toolkit/issues/292) Fix broken pagination when an EPUB uses `overflow-x: hidden`.
---
* Fix #292
> Fix broken pagination when an EPUB uses `overflow-x: hidden`

- CHANGELOG.md
- readium/navigator/src/main/java/org/readium/r2/navigator/R2WebView.kt
- readium/navigator/src/main/java/org/readium/r2/navigator/epub/EpubNavigatorViewModel.kt
- readium/navigator/src/main/java/org/readium/r2/navigator/pager/R2EpubPageFragment.kt
* Fixed scroll inertia when scrolling an EPUB.
---
Note that this is only fixed with the new Settings API, because it requires invalidating the resource pager which is not supported by the legacy one.
https://user-images.githubusercontent.com/58686775/205715747-6e5f6430-3b06-4ef0-a705-abe23f1b3340.mov
> Fix scroll inertia when scrolling an EPUB

- readium/navigator/src/main/java/org/readium/r2/navigator/epub/EpubNavigatorFragment.kt
- readium/navigator/src/main/java/org/readium/r2/navigator/epub/EpubNavigatorViewModel.kt
- readium/navigator/src/main/java/org/readium/r2/navigator/epub/HtmlInjector.kt
- readium/navigator/src/main/java/org/readium/r2/navigator/epub/WebViewServer.kt
As [LCP copy rights are not yet implemented](https://github.com/readium/kotlin-toolkit/issues/299#issuecomment-1315643577) in the Kotlin toolkit, the text selection is disabled in an LCP protected EPUB.
This is an issue for many implementers that want to support highlighting an LCP protected EPUB. This PR adds a new `disableSelectionWhenProtected` EPUB config option to disable the protection without having to fork the toolkit.
However, if you choose to use it, you MUST remove the Copy and Share selection menu items in your app. Otherwise, you will void the EDRLab certification for your application.
> Allow to bypass the selection protection with LCP

- readium/streamer/src/main/java/org/readium/r2/streamer/parser/epub/AccessibilityAdapter.kt
- readium/streamer/src/test/resources/org/readium/r2/streamer/parser/epub/package/accessibility-epub3.opf
The EPUB parser was not properly parsing the accessibility profile when using `<link>` instead of `<meta>`.
> Fix parsing of the EPUB accessibility profile

- .github/workflows/publish.yml
- README.md
- build.gradle.kts
- docs/migration-guide.md
- readium/adapters/pdfium/build.gradle.kts
- readium/adapters/pdfium/pdfium-document/build.gradle.kts
- readium/adapters/pdfium/pdfium-navigator/build.gradle.kts
- readium/adapters/pspdfkit/build.gradle.kts
- readium/adapters/pspdfkit/pspdfkit-document/build.gradle.kts
- readium/adapters/pspdfkit/pspdfkit-navigator/build.gradle.kts
- readium/lcp/build.gradle.kts
- readium/navigator-media2/build.gradle.kts
- readium/navigator/build.gradle.kts
- readium/opds/build.gradle.kts
- readium/shared/build.gradle.kts
- readium/streamer/build.gradle.kts
- scripts/publish-module.gradle
- scripts/publish-root.gradle
- settings.gradle.kts
Here's the Sonatype JIRA issue requesting the creation of the Readium repo: https://issues.sonatype.org/browse/OSSRH-85964
I followed these instructions to setup Maven Central publishing: https://getstream.io/blog/publishing-libraries-to-mavencentral-2021/
> Publish to Maven Central

- CHANGELOG.md
- readium/navigator/src/main/java/org/readium/r2/navigator/epub/EpubNavigatorFragment.kt
- readium/navigator/src/main/java/org/readium/r2/navigator/epub/EpubNavigatorViewModel.kt
- readium/navigator/src/main/java/org/readium/r2/navigator/epub/EpubSettings.kt
* New `EPUBNavigatorFragment.Configuration.useReadiumCssFontSize` option to revert to the 2.2.0 strategy for setting the font size of reflowable EPUB publications.
* The native font size strategy introduced in 2.3.0 uses the Android web view's [`WebSettings.textZoom`](https://developer.android.com/reference/android/webkit/WebSettings#setTextZoom(int)) property to adjust the font size. 2.2.0 was using Readium CSS's [`--USER__fontSize` variable](https://readium.org/readium-css/docs/CSS12-user_prefs.html#font-size).
* `WebSettings.textZoom` will work with more publications than `--USER__fontSize`, even the ones poorly authored. However the page width is not adjusted when changing the font size to keep the optimal line length.
> EPUB: Option to revert to the 2.2.0 font size strategy

- Makefile
- readium/shared/src/main/java/org/readium/r2/shared/publication/services/content/iterators/HtmlResourceContentIterator.kt
- readium/shared/src/test/java/org/readium/r2/shared/publication/services/content/iterators/HtmlResourceContentIteratorTest.kt
Additional fixes for more HTML edge cases:
* Parse inline text nodes in an element containing more children elements.
* Locate starting location when in an empty element.
* Improve handling of whitespaces in `Locator.Text`.
> Fix HTML resource content iterator

- readium/navigator/src/main/java/org/readium/r2/navigator/epub/EpubPreferencesEditor.kt
Hyphens is true when textAlign is justified even if no preference is set.
> Fix the hyphens setting

- readium/lcp/src/main/java/org/readium/r2/lcp/LcpDecryptor.kt
CBC range decryption was completely wrong since #337 was merged into `v3`.
> Fix regression in LcpDecryptor

- .idea/compiler.xml
- .idea/kotlinc.xml
- CHANGELOG.md
- readium/navigator/src/main/java/org/readium/r2/navigator/R2BasicWebView.kt
- readium/navigator/src/main/java/org/readium/r2/navigator/pager/R2EpubPageFragment.kt
* [#360](https://github.com/readium/kotlin-toolkit/issues/360) Fix EPUB JavaScript interface injection when rotating the screen on some devices.
---
* Fix #360 
I partially reverted https://github.com/readium/r2-navigator-kotlin/pull/191. It looks like using `addJavascriptInterface()` from `onAttachedToWindow()` sometimes fail on some devices.
> Fix JavaScript interface injection when rotating the screen

- docs/guides/index.md
- docs/guides/media-navigator.md
- docs/guides/tts.md
- readium/navigator/src/main/java/org/readium/r2/navigator/media3/api/TextAwareMediaNavigator.kt
- readium/navigator/src/main/java/org/readium/r2/navigator/media3/syncmedia/GuidedAudioNavigator.kt
- readium/navigator/src/main/java/org/readium/r2/navigator/media3/tts/TtsNavigator.kt
- readium/navigator/src/main/java/org/readium/r2/navigator/media3/tts/TtsNavigatorFactory.kt
- readium/navigator/src/main/java/org/readium/r2/navigator/media3/tts/android/AndroidTtsEngine.kt
- readium/navigator/src/main/java/org/readium/r2/navigator/media3/tts/android/AndroidTtsEngineProvider.kt
- readium/shared/src/main/java/org/readium/r2/shared/publication/services/content/iterators/HtmlResourceContentIterator.kt
- test-app/src/main/java/org/readium/r2/testapp/reader/ReaderRepository.kt
- test-app/src/main/java/org/readium/r2/testapp/reader/VisualReaderFragment.kt
- test-app/src/main/java/org/readium/r2/testapp/reader/tts/TtsViewModel.kt
- test-app/src/main/res/values/strings.xml
* Update the TTS user guide.
* Add a Media Navigator user guide.
* Minor changes in the Media navigator interfaces.
* Refactor the `LanguageMissingData` TTS error.
* Remove the `preventProgressionSaving` logic from the Test App.
> Add user guides for TTS and Media Navigators

- readium/lcp/src/main/java/org/readium/r2/lcp/service/LicensesService.kt
- readium/navigator/src/main/java/org/readium/r2/navigator/media/MediaSessionNavigator.kt
- readium/shared/src/main/java/org/readium/r2/shared/publication/Manifest.kt
- readium/shared/src/test/java/org/readium/r2/shared/publication/ManifestTest.kt
- readium/streamer/src/main/java/org/readium/r2/streamer/ParserAssetFactory.kt
- readium/streamer/src/main/java/org/readium/r2/streamer/parser/readium/ReadiumWebPubParser.kt
* Don't remove the `self` link anymore, when parsing a packaged publication. They are not supposed to contain a `self` link with an absolute URL.
* Fix file extensions in the LCP service.
* Restore visibility of `MediaSessionNavigator` properties (hiding them was a mistake when migrating to the explicit API mode).
> Simplify RWPM parsing for packaged publications

- readium/navigator/src/main/java/org/readium/r2/navigator/media3/tts/TtsEngineFacade.kt
- readium/shared/src/main/java/org/readium/r2/shared/publication/Locator.kt
- readium/shared/src/test/java/org/readium/r2/shared/publication/LocatorTest.kt
* Fix issue when computing a substring of a `Locator.Text`, were the char offsets were incorrect.
* Fix terminating the current TTS task.
* Sometimes we received events for a previous task, which interrupted the current task too early. I fixed it by checking for the task ID first.
> Bugfixes for TTS

- CHANGELOG.md
- docs/migration-guide.md
- readium/shared/src/main/java/org/readium/r2/shared/publication/Locator.kt
- readium/shared/src/main/java/org/readium/r2/shared/util/Url.kt
- readium/shared/src/test/java/org/readium/r2/shared/publication/LocatorTest.kt
- readium/shared/src/test/java/org/readium/r2/shared/util/UrlTest.kt
* `Link` and `Locator`'s `href` are normalized as valid URLs to improve interoperability with the Readium Web toolkits.
* **You MUST migrate your database if you were persisting HREFs and Locators**. Take a look at [the migration guide](docs/migration-guide.md) for guidance.
:warning: This requires a database migration in your application, if you were persisting `Locator` objects.
In Readium v2.x, a `Link` or `Locator`'s `href` could be either:
* a valid absolute URL for a streamed publication, e.g. `https://domain.com/isbn/dir/my%20chapter.html`,
* a percent-decoded path for a local archive such as an EPUB, e.g. `/dir/my chapter.html`.
* Note that it was relative to the root of the archive (`/`).
To improve the interoperability with other Readium toolkits (in particular the Readium Web …
> Helper to migrate legacy HREFs

- readium/shared/src/main/java/org/readium/r2/shared/resource/DefaultArchiveFactory.kt
- readium/shared/src/main/java/org/readium/r2/shared/resource/MediaTypeExt.kt
- readium/shared/src/main/java/org/readium/r2/shared/util/archive/channel/ChannelZipContainer.kt
This restores [this fix](https://github.com/readium/r2-shared-kotlin/commit/dd0780268539aa2376f89c84a7ab61fed83d62a5#diff-be198afd4545d50e95947243a040c05085a51ae67be0a16f45851106955df941) which was lost during the media type refactoring.
> Prevent out of memory errors when sniffing a media type

- readium/shared/src/main/java/org/readium/r2/shared/util/archive/channel/compress/utils/IOUtils.java
[`LinkOption` is only available since API 26](https://developer.android.com/reference/java/nio/file/LinkOption), so `ChannelZipContainer` crashed with:
```
java.lang.NoClassDefFoundError: Failed resolution of: [Ljava/nio/file/LinkOption;
at org.readium.r2.shared.util.archive.channel.compress.utils.IOUtils.<clinit>(IOUtils.java:46)
at org.readium.r2.shared.util.archive.channel.compress.archivers.zip.ZipFile.tryToLocateSignature(ZipFile.java:1392)
at org.readium.r2.shared.util.archive.channel.compress.archivers.zip.ZipFile.positionAtEndOfCentralDirectoryRecord(ZipFile.java:1071)
at org.readium.r2.shared.util.archive.channel.compress.archivers.zip.ZipFile.positionAtCentralDirectory(ZipFile.java:941)
at org.readium.r2.shared.util.archive.channel.compress.archivers.zip.ZipFile.populateFromCentr …
```
> Fix crash with `ChannelZipContainer` before API 26

- CHANGELOG.md
- readium/shared/src/main/java/org/readium/r2/shared/extensions/Map.kt
- readium/shared/src/main/java/org/readium/r2/shared/util/Try.kt
- readium/shared/src/main/java/org/readium/r2/shared/util/downloads/foreground/ForegroundDownloadManager.kt
- readium/shared/src/main/java/org/readium/r2/shared/util/http/DefaultHttpClient.kt
- readium/shared/src/main/java/org/readium/r2/shared/util/http/HttpClient.kt
- readium/shared/src/main/java/org/readium/r2/shared/util/http/HttpHeaders.kt
- readium/shared/src/main/java/org/readium/r2/shared/util/http/HttpRequest.kt
* `DefaultHttClient.additionalHeaders` is deprecated. Set all the headers when creating a new `HttpRequest`, or modify outgoing requests in `DefaultHttpClient.Callback.onStartRequest()`.
> Support multiple values for HTTP header with same key

- CHANGELOG.md
- readium/adapters/pdfium/pdfium-navigator/src/main/java/org/readium/adapters/pdfium/navigator/PdfiumDocumentFragment.kt
- readium/navigator/src/main/java/org/readium/r2/navigator/DummyPublication.kt
- readium/navigator/src/main/java/org/readium/r2/navigator/epub/EpubNavigatorFragment.kt
- readium/navigator/src/main/java/org/readium/r2/navigator/image/ImageNavigatorFragment.kt
- readium/navigator/src/main/java/org/readium/r2/navigator/pdf/PdfNavigatorFragment.kt
- readium/navigator/src/main/java/org/readium/r2/navigator/tts/AndroidTtsEngine.kt
- readium/navigator/src/main/java/org/readium/r2/navigator/tts/PublicationSpeechSynthesizer.kt
- readium/navigator/src/main/java/org/readium/r2/navigator/tts/TtsEngine.kt
- test-app/src/main/java/org/readium/r2/testapp/Application.kt
- test-app/src/main/java/org/readium/r2/testapp/bookshelf/BookshelfViewModel.kt
- test-app/src/main/java/org/readium/r2/testapp/reader/EpubReaderFragment.kt
- test-app/src/main/java/org/readium/r2/testapp/reader/ImageReaderFragment.kt
- test-app/src/main/java/org/readium/r2/testapp/reader/PdfReaderFragment.kt
- test-app/src/main/java/org/readium/r2/testapp/reader/ReaderActivity.kt
- test-app/src/main/java/org/readium/r2/testapp/reader/ReaderViewModel.kt
* Added dummy navigator fragment factories to prevent crashes caused by Android restoring the fragments after a process death.
* To use it, set the dummy fragment factory when you don't have access to the `Publication` instance. Then, either finish the `Activity` or pop the fragment from the UI before it resumes.
```kotlin
override fun onCreate(savedInstanceState: Bundle?) {
val publication = model.publication ?: run {
childFragmentManager.fragmentFactory = EpubNavigatorFragment.createDummyFactory()
super.onCreate(savedInstanceState)
requireActivity().finish()
// or
navController?.popBackStack()
return
}
// Create the real navigator factory as usual...
}
```
---
Fix #395
> Fix crash when restoring the fragment hierarchy after process death

- readium/shared/src/main/java/org/readium/r2/shared/util/CoroutineQueue.kt
- test-app/src/main/java/org/readium/r2/testapp/utils/CoroutineQueue.kt
`CoroutineQueue` could crash during initialization if the tasks coroutine executes before the object is fully initialized. Moving the `tasks` property above `init` should fix the issue.
```
java.lang.NullPointerException: Attempt to invoke interface method 'kotlinx.coroutines.channels.ChannelIterator kotlinx.coroutines.channels.Channel.iterator()' on a null object reference
at org.readium.r2.shared.util.CoroutineQueue$1.invokeSuspend(CoroutineQueue.kt:36)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
```
> Fix crash in `CoroutineQueue`

- readium/adapters/pspdfkit/navigator/src/main/java/org/readium/adapter/pspdfkit/navigator/PsPdfKitDocumentFragment.kt
- readium/navigator/src/main/java/org/readium/r2/navigator/NavigatorFragment.kt
- readium/navigator/src/main/java/org/readium/r2/navigator/epub/EpubNavigatorFragment.kt
- readium/navigator/src/main/java/org/readium/r2/navigator/image/ImageNavigatorFragment.kt
- readium/navigator/src/main/java/org/readium/r2/navigator/pdf/PdfNavigatorFragment.kt
* Disable PSPDFKit's Share action with protected publications.
* **Copy** was already [disabled here](https://github.com/readium/kotlin-toolkit/blob/17423811fa962ac3da8f0ecd58b69c0e28c1a2a7/readium/adapters/pspdfkit/navigator/src/main/java/org/readium/adapter/pspdfkit/navigator/PsPdfKitDocumentFragment.kt#L223-L225) but this didn't remove the Share text selection action.
* Prevent screenshots and text selection from the task switcher for protected publications.
> Additional copy preventions for protected publications

- readium/shared/src/main/java/org/readium/r2/shared/OptIn.kt
- readium/streamer/src/main/java/org/readium/r2/streamer/PublicationOpener.kt
- readium/streamer/src/main/java/org/readium/r2/streamer/parser/PublicationParser.kt
- readium/streamer/src/main/java/org/readium/r2/streamer/parser/pdf/PdfParser.kt
- test-app/src/main/java/org/readium/r2/testapp/Readium.kt
Adds a composite `PublicationParser` to remove the construction arguments required by `PublicationOpener` to create the parsers.
> Simplify the `PublicationOpener` by adding a `DefaultPublicationParser`

- readium/navigator/src/main/java/org/readium/r2/navigator/VisualNavigator.kt
- readium/navigator/src/main/java/org/readium/r2/navigator/media/MediaSessionNavigator.kt
- readium/shared/src/main/java/org/readium/r2/shared/util/downloads/foreground/ForegroundDownloadManager.kt
* Fixed deprecated notices
* Restore default parameters for `MediaNavigator.goForward` and `goBackward` APIs.
* Prevent crash in `ForegroundDownloadManager` when the download folder doesn't exist.
> Minor fixes

- readium/shared/src/main/java/org/readium/r2/shared/util/asset/Defaults.kt
- readium/shared/src/main/java/org/readium/r2/shared/util/format/Format.kt
- readium/shared/src/main/java/org/readium/r2/shared/util/format/Sniffers.kt
- readium/shared/src/test/java/org/readium/r2/shared/util/asset/AssetSnifferTest.kt
- readium/shared/src/test/java/org/readium/r2/shared/util/format/DefaultSniffersTest.kt
This adds a couple of media type sniffers that can guess CSS and JS files from their content types and/or file extensions.
> Implement sniffing of CSS and JS files

- test-app/src/main/AndroidManifest.xml
This `AndroidManifest.xml` flag was added [to address an issue with the HTTP server](https://github.com/readium/r2-testapp-kotlin/pull/298). As [we remove the HTTP server](https://github.com/readium/kotlin-toolkit/pull/259), it's not needed anymore. Let's remove it as it [causes some issues](https://github.com/readium/kotlin-toolkit/issues/440).
* Fix #440
> Remove `android:clearTaskOnLaunch`

- CHANGELOG.md
- readium/lcp/src/main/java/org/readium/r2/lcp/LcpService.kt
- readium/lcp/src/main/java/org/readium/r2/lcp/service/LicensesService.kt
`LcpService.injectLicenseDocument` enables apps to download publications with a custom engine (possibly working in background) and then manually inject the license document into the publication file.
> Add LcpService.injectLicenseDocument

- readium/shared/src/main/java/org/readium/r2/shared/util/asset/AssetSniffer.kt
- readium/shared/src/main/java/org/readium/r2/shared/util/format/Format.kt
- readium/shared/src/main/java/org/readium/r2/shared/util/format/Sniffers.kt
- readium/shared/src/main/java/org/readium/r2/shared/util/format/Sniffing.kt
FormatSniffers were able to indefinitely correct each other by returning a different media type. Now:
- `sniffContent` can correct `sniffHints`
- `sniffContent` cannot correct a previous call to `sniffContent`, meaning it must add a specification to be able to change the media type or the file extension.
> Prevent infinite recursion in format sniffing

- readium/lcp/src/main/java/org/readium/r2/lcp/LcpService.kt
- readium/lcp/src/main/java/org/readium/r2/lcp/service/LicensesService.kt
MediaType is known from the license document.
> Simplify LcpService.injectLicense

- readium/lcp/src/main/java/org/readium/r2/lcp/LcpError.kt
- readium/lcp/src/main/java/org/readium/r2/lcp/service/LicensesService.kt
- readium/lcp/src/main/java/org/readium/r2/lcp/service/NetworkService.kt
- Check cancellation in `acquirePublication`
- Try not to catch `CancellationException`s
> Various improvements in LcpService

- gradle/libs.versions.toml
- readium/shared/src/test/java/org/readium/r2/shared/publication/services/content/iterators/HtmlResourceContentIteratorTest.kt
Jsoup 1.16.2 requires core library desugaring, otherwise it crashes on Android 7 devices when opening the EPUB navigator.
See https://github.com/jhy/jsoup/issues/2022#issuecomment-1783931119
Before enabling desugaring, we need to assess its impact on the toolkit. Until we do, I downgraded this dependency.
> Downgrade to jsoup 1.16.1

- readium/lcp/src/main/java/org/readium/r2/lcp/LcpContentProtection.kt
- readium/lcp/src/main/java/org/readium/r2/lcp/LcpError.kt
- readium/lcp/src/main/java/org/readium/r2/lcp/license/LicenseValidation.kt
- readium/lcp/src/main/java/org/readium/r2/lcp/service/LicensesService.kt
- test-app/src/main/java/org/readium/r2/testapp/domain/LcpUserError.kt
Return LcpError.MissingCredentials instead of throwing CancellationException if user cancels authentication
> Fix opening LCP-protected publication in restricted mode

- CHANGELOG.md
- readium/navigator-media2/src/main/java/org/readium/navigator/media2/MediaNavigator.kt
- readium/navigator/src/main/java/org/readium/r2/navigator/Navigator.kt
- readium/navigator/src/main/java/org/readium/r2/navigator/R2BasicWebView.kt
- readium/navigator/src/main/java/org/readium/r2/navigator/VisualNavigator.kt
- readium/navigator/src/main/java/org/readium/r2/navigator/epub/EpubNavigatorFragment.kt
- readium/navigator/src/main/java/org/readium/r2/navigator/image/ImageNavigatorFragment.kt
- readium/navigator/src/main/java/org/readium/r2/navigator/media/MediaSessionNavigator.kt
- readium/navigator/src/main/java/org/readium/r2/navigator/pdf/PdfNavigatorFragment.kt
- readium/navigators/media/audio/src/main/java/org/readium/navigator/media/audio/AudioNavigator.kt
- readium/navigators/media/tts/src/main/java/org/readium/navigator/media/tts/TtsNavigator.kt
* All the `completion` parameters of the `Navigator` APIs are removed.
---
`completion` is not idiomatic for Kotlin (copied from the Swift toolkit), and these parameters were not used in most navigators.
> Remove `completion` from `Navigator` APIs

- readium/navigator/src/main/java/org/readium/r2/navigator/R2BasicWebView.kt
- readium/navigator/src/main/java/org/readium/r2/navigator/epub/EpubNavigatorFragment.kt
- readium/navigator/src/main/java/org/readium/r2/navigator/epub/EpubNavigatorViewModel.kt
- readium/navigator/src/main/java/org/readium/r2/navigator/pager/R2EpubPageFragment.kt
- readium/navigator/src/main/java/org/readium/r2/navigator/pager/R2FXLPageFragment.kt
- readium/navigator/src/main/java/org/readium/r2/navigator/pager/R2PagerAdapter.kt
- readium/shared/src/main/java/org/readium/r2/shared/publication/Publication.kt
- readium/shared/src/main/java/org/readium/r2/shared/util/format/Sniffers.kt
While loading the EPUB navigator's initial locator, calling certain APIs too early, like `submitPreferences()`, can cause us to lose it. This happens because the `currentLocator` goes through various temporary positions before settling on the requested initial locator. If we invalidate the view pager while loading, the pending locator is cleared and replaced with the current state of the `currentLocator`.
I solved this by adding a `State` in the `EpubNavigatorFragment` to monitor the loading of pending locators. `currentLocator` will only update after the requested locator finishes loading.
> Prevent reporting the current position while loading a locator

- buildSrc/src/main/kotlin/readium.library-conventions.gradle.kts
- docs/migration-guide.md
- gradle/libs.versions.toml
- readium/shared/src/test/java/org/readium/r2/shared/publication/services/content/iterators/HtmlResourceContentIteratorTest.kt
- test-app/build.gradle.kts
If you target Android devices running below API 26, you now must enable [core library desugaring](https://developer.android.com/studio/write/java8-support#library-desugaring) in your application module.
This is required by some of our third-party dependencies, such as `kotlinx-datetime` or `jsoup`.
> Enable core library desugaring

- readium/navigator/src/main/java/org/readium/r2/navigator/R2BasicWebView.kt
EPUB `noteref` links containing nested HTML elements were not always reported as footnotes, as we were checking the `epub:type="noteref"` attribute on the `targetElement`, which might not be the `<a>`.
For example with `<a epub:type="noteref" href="notas.xhtml#nt1" id="rf1"><sup>1</sup></a>.</p>`,
`interactiveElement` is the whole `<a>`, while `targetElement` might be `<sup>1</sup>`, depending where we clicked.
> Fix handling EPUB `noteref` with nested elements

- CHANGELOG.md
- readium/navigator/src/main/java/org/readium/r2/navigator/R2BasicWebView.kt
* [#325](https://github.com/readium/kotlin-toolkit/issues/325) Top EPUB selections no longer break when dragging the selection handles.
---
Technically the bug is still there (as it requires a fix in the Android WebView), but as the viewport is not scrolling, we can recover gracefully by continuing dragging.
https://github.com/readium/kotlin-toolkit/assets/58686775/a153c43c-abbb-45f6-8eca-68c09ea9db8e
> Fix broken EPUB selection in paginated mode

- CHANGELOG.md
- readium/navigator/src/main/java/org/readium/r2/navigator/epub/EpubNavigatorFragment.kt
- readium/navigator/src/main/java/org/readium/r2/navigator/pager/R2EpubPageFragment.kt
- readium/opds/src/main/java/org/readium/r2/opds/OPDS1Parser.kt
Sometimes we need to trigger JavaScript during a configuration change. For example if the user submit new preferences (use case: switching the EPUB `theme` when the system mode changes).
This fails because the JavaScript layer (`readium` namespace) is not yet loaded.
As a workaround, we schedule incoming JavaScript requests until the webview page is loaded again.
> Fix applying preferences while recreating EPUB fragments

- .idea/.gitignore
- CHANGELOG.md
- readium/lcp/src/main/AndroidManifest.xml
- readium/lcp/src/main/java/org/readium/r2/lcp/LcpService.kt
- readium/lcp/src/main/java/org/readium/r2/lcp/service/DeviceService.kt
* [#493](https://github.com/readium/kotlin-toolkit/discussions/493) The LCP module does not require the Bluetooth permissions anymore to derive the device name.
---
* Closes #493
> Change LCP device name strategy

- CHANGELOG.md
- readium/lcp/src/main/java/org/readium/r2/lcp/license/LicenseValidation.kt
* [#509](https://github.com/readium/kotlin-toolkit/issues/509) Support for the new 2.x LCP Profiles.
---
* Closes #509
> Support for the new 2.x LCP Profiles

- CHANGELOG.md
- readium/shared/src/main/java/org/readium/r2/shared/util/archive/ArchiveProperties.kt
- readium/shared/src/test/java/org/readium/r2/shared/util/resource/PropertiesTest.kt
* The `Link` property key for archive-based publication assets (e.g. an EPUB/ZIP) is now `https://readium.org/webpub-manifest/properties#archive` instead of `archive`.
> Rename `archive` Link property

- readium/lcp/src/main/java/org/readium/r2/lcp/service/LicensesService.kt
Some HTTP servers send wrong media types when downloading an LCP protected publication. For example returning `application/epub+zip` when downloading an LCPDF.
This failed the media type sniffing as we used both the license and HTTP server media types as hints.
Instead, now we use the license media type, and only the HTTP server media type as a fallback when missing.
> Fix sniffing media types when acquiring an LCP publication

- readium/lcp/src/main/java/org/readium/r2/lcp/LcpService.kt
- readium/lcp/src/main/java/org/readium/r2/lcp/service/LicensesService.kt
This is useful to get LCP metadata without unlocking a publication.
> Add a retrieveLicenseDocument method to LcpService

- readium/adapters/exoplayer/audio/src/main/java/org/readium/adapter/exoplayer/audio/ExoPlayerEngine.kt
- readium/navigators/media/audio/src/main/java/org/readium/navigator/media/audio/AudioEngine.kt
- readium/navigators/media/tts/src/main/java/org/readium/navigator/media/tts/TtsEngine.kt
- readium/navigators/media/tts/src/main/java/org/readium/navigator/media/tts/TtsNavigator.kt
Closing a Media 3 adapter is not supposed to close the underlying player because it's still being used by the `AudioEngine` which assumes that the player will never reach the IDLE state again after preparing.
> Prevent crash in case of misuse of AudioEngine.asPlayer().release

- readium/adapters/pdfium/document/src/main/java/org/readium/adapter/pdfium/document/PdfiumDocument.kt
- readium/adapters/pspdfkit/document/src/main/java/org/readium/adapter/pspdfkit/document/PsPdfKitDocument.kt
- readium/shared/src/main/java/org/readium/r2/shared/publication/Publication.kt
- readium/shared/src/main/java/org/readium/r2/shared/publication/PublicationServicesHolder.kt
- readium/shared/src/main/java/org/readium/r2/shared/publication/services/search/SearchService.kt
- readium/shared/src/main/java/org/readium/r2/shared/util/Closeable.kt
- readium/shared/src/main/java/org/readium/r2/shared/util/asset/Asset.kt
- readium/shared/src/main/java/org/readium/r2/shared/util/cache/Cache.kt
- readium/shared/src/main/java/org/readium/r2/shared/util/content/ContentResource.kt
- readium/shared/src/main/java/org/readium/r2/shared/util/data/Caching.kt
- readium/shared/src/main/java/org/readium/r2/shared/util/data/Container.kt
- readium/shared/src/main/java/org/readium/r2/shared/util/data/Reading.kt
- readium/shared/src/main/java/org/readium/r2/shared/util/file/DirectoryContainer.kt
- readium/shared/src/main/java/org/readium/r2/shared/util/file/FileResource.kt
- readium/shared/src/main/java/org/readium/r2/shared/util/http/HttpContainer.kt
- readium/shared/src/main/java/org/readium/r2/shared/util/http/HttpResource.kt
- readium/shared/src/main/java/org/readium/r2/shared/util/pdf/PdfDocument.kt
- readium/shared/src/main/java/org/readium/r2/shared/util/resource/FallbackResource.kt
- readium/shared/src/main/java/org/readium/r2/shared/util/resource/InMemoryResource.kt
- readium/shared/src/main/java/org/readium/r2/shared/util/resource/LazyResource.kt
- readium/shared/src/main/java/org/readium/r2/shared/util/resource/Resource.kt
- readium/shared/src/main/java/org/readium/r2/shared/util/resource/SingleResourceContainer.kt
- readium/shared/src/main/java/org/readium/r2/shared/util/resource/SynchronizedResource.kt
- readium/shared/src/main/java/org/readium/r2/shared/util/resource/TransformingContainer.kt
- readium/shared/src/main/java/org/readium/r2/shared/util/zip/FileZipContainer.kt
- readium/shared/src/main/java/org/readium/r2/shared/util/zip/StreamingZipContainer.kt
- readium/shared/src/test/java/org/readium/r2/shared/util/format/TestContainer.kt
- readium/streamer/src/test/java/org/readium/r2/streamer/parser/epub/EpubPositionsServiceTest.kt
Remove `SuspendingCloseable` because it does not make much sense and is a bit dangerous: freeing resources is not something you want to be cancellable.
> Remove SuspendingCloseable

- readium/lcp/src/main/java/org/readium/r2/lcp/LcpDecryptor.kt
- readium/lcp/src/main/java/org/readium/r2/lcp/license/License.kt
- readium/navigator/src/main/java/org/readium/r2/navigator/R2BasicWebView.kt
- readium/navigator/src/main/java/org/readium/r2/navigator/epub/EpubNavigatorFragment.kt
- readium/navigator/src/main/java/org/readium/r2/navigator/extensions/Publication.kt
- readium/navigator/src/main/java/org/readium/r2/navigator/media/MediaService.kt
- readium/opds/src/main/java/org/readium/r2/opds/OPDS1Parser.kt
- readium/shared/src/main/java/org/readium/r2/shared/MediaOverlays.kt
- readium/shared/src/main/java/org/readium/r2/shared/publication/Href.kt
- readium/shared/src/main/java/org/readium/r2/shared/publication/Link.kt
- readium/shared/src/main/java/org/readium/r2/shared/publication/Manifest.kt
- readium/shared/src/main/java/org/readium/r2/shared/publication/services/content/iterators/HtmlResourceContentIterator.kt
- readium/shared/src/main/java/org/readium/r2/shared/publication/services/search/StringSearchService.kt
- readium/shared/src/main/java/org/readium/r2/shared/util/Url.kt
- readium/shared/src/main/java/org/readium/r2/shared/util/data/Caching.kt
- readium/shared/src/main/java/org/readium/r2/shared/util/http/HttpContainer.kt
- readium/shared/src/main/java/org/readium/r2/shared/util/resource/SingleResourceContainer.kt
- readium/shared/src/test/java/org/readium/r2/shared/util/UrlTest.kt
- readium/shared/src/test/java/org/readium/r2/shared/util/format/TestContainer.kt
- readium/streamer/src/main/java/org/readium/r2/streamer/parser/audio/AudioParser.kt
- readium/streamer/src/main/java/org/readium/r2/streamer/parser/epub/EpubDeobfuscator.kt
- readium/streamer/src/main/java/org/readium/r2/streamer/parser/epub/NavigationDocumentParser.kt
- readium/streamer/src/main/java/org/readium/r2/streamer/parser/epub/NcxParser.kt
- readium/streamer/src/main/java/org/readium/r2/streamer/parser/epub/SmilParser.kt
- readium/streamer/src/main/java/org/readium/r2/streamer/parser/image/ImageParser.kt
- readium/streamer/src/main/java/org/readium/r2/streamer/parser/readium/ReadiumWebPubParser.kt
- readium/streamer/src/test/java/org/readium/r2/streamer/parser/epub/EpubPositionsServiceTest.kt
- test-app/src/main/java/org/readium/r2/testapp/bookshelf/BookshelfFragment.kt
- test-app/src/main/java/org/readium/r2/testapp/outline/BookmarksFragment.kt
Normalize URLs when comparing them following these rules:
* Scheme is lower case.
* Paths must only percent-encode required characters.
* Relative paths (e.g. `..`) are resolved.
The reason for this change is that some EPUBs encode unreserved characters which breaks locating a Link from an HREF.
For example both of these are valid relative URLs which point to the same resource:
* `Text/Ces_choses_qu'on_laisse.xhtml`
* `Text/Ces_choses_qu%27on_laisse.xhtml`
> Normalize URLs

- readium/shared/src/main/java/org/readium/r2/shared/util/zip/StreamingZipContainer.kt
`Resource`s are neither thread-safe nor coroutine-safe BUT several resources from the same container can be used at the same time (for instance by the WebView). Java `ZipFile` is thread-safe but the one from Apache Compress is not.
_Should_ fix #526
> Control access to ZipFile with a mutex in StreamingZipContainer

- readium/adapters/pspdfkit/navigator/src/main/java/org/readium/adapter/pspdfkit/navigator/PsPdfKitDocumentFragment.kt
There are some cases (not reproducible in the Test App) where the PSPDFKit settings are not applied when the PDF view is recreated.
For example, it can happen that the RTL page binding is not taken into account after a configuration change triggered by forcing an orientation in the parent `Activity` with `setRequestedOrientation()`.
> Fix applying the PSPDFKit settings on configuration changes

- CHANGELOG.md
- readium/navigators/media/audio/src/main/java/org/readium/navigator/media/audio/AudioNavigator.kt
* Fixed computing the total progression of audiobook locators.
> Fix audiobook locators' total progression

- CHANGELOG.md
- readium/navigator/src/main/java/org/readium/r2/navigator/epub/EpubNavigatorFragment.kt
* Fixed starting the TTS from the current resource in a fixed-layout EPUB.
---
The current visible element API did not return the current locator in an FXL, causing this issue.
> Fix TTS in a fixed-layout EPUB

- readium/navigator/src/main/java/org/readium/r2/navigator/R2BasicWebView.kt
- readium/navigator/src/main/java/org/readium/r2/navigator/epub/EpubNavigatorFragment.kt
- readium/navigator/src/main/java/org/readium/r2/navigator/epub/EpubNavigatorViewModel.kt
Use JavaScript `preventDefaultBehavior` to prevent the WebView from loading a footnote link that has already been handled instead of an unreliable workaround.
> Improve footnotes handling

- CHANGELOG.md
- readium/lcp/src/main/java/org/readium/r2/lcp/LcpDecryptor.kt
- readium/shared/src/main/java/org/readium/r2/shared/util/io/CountingInputStream.kt
Fixes `IndexOutOfBoundsException` occurring when the `originalLength` reported in `META-INF/encryption.xml` is incorrect.
> Fix CBC decryption when originalLength is wrong

- readium/adapters/exoplayer/audio/src/main/java/org/readium/adapter/exoplayer/audio/ExoPlayerEngine.kt
We are currently waiting for the first audio resource to buffer before considering the `ExoPlayerEngine` initialized. This can significantly slow down the opening of the audio navigator in case of network latency.
This change will return the audio navigator as soon as we enter the ExoPlayer buffering state. Integrators can then display a spinner to indicate that the audiobook is not yet ready or delay opening the reader to maintain the current behavior.
> Speed up initialization of `ExoPlayerEngine`

- CHANGELOG.md
- readium/navigator/src/main/java/org/readium/r2/navigator/epub/EpubNavigatorFragment.kt
- readium/navigator/src/main/java/org/readium/r2/navigator/epub/EpubNavigatorViewModel.kt
* Fixed a race condition causing EPUB decorations to be applied twice when opening a publication.
---
If the application called `applyDecorations()` when a web view is loaded but its resource not yet loaded, it caused the decorations to be applied twice. You can reproduce this by opening several times a publication with a highlight, until you see that the color is darker (two identical decorations on top of each other). I fixed it by only applying the decorations in fully loaded resources.
I also reapply the Readium CSS properties when the web view is loaded, in case they changed since their first static injection in the HTML document.
> Fix a race condition when initializing the EPUB navigator

- CHANGELOG.md
- readium/navigator/src/main/java/org/readium/r2/navigator/R2BasicWebView.kt
- readium/navigator/src/main/java/org/readium/r2/navigator/epub/EpubNavigatorFragment.kt
- readium/navigator/src/main/java/org/readium/r2/navigator/epub/EpubNavigatorViewModel.kt
- readium/navigator/src/main/java/org/readium/r2/navigator/pager/R2EpubPageFragment.kt
- readium/navigator/src/main/java/org/readium/r2/navigator/pager/R2RTLViewPager.java
I'm looking to add the equivalent functionality that was added here: https://github.com/readium/swift-toolkit/pull/531
> feat: add option to disable horizontal swiping when scroll is true.

- readium/shared/src/main/java/org/readium/r2/shared/util/xml/XmlParser.kt
- readium/shared/src/test/java/org/readium/r2/shared/util/xml/XmlParserTest.kt
https://github.com/readium/kotlin-toolkit/issues/627
I have addressed the issue I previously created.  
Fixed a bug where text was incorrectly parsed when `CDATA` was present in the XML file.
> Modified XmlParser to correctly parse CDATA.

- CHANGELOG.md
- readium/shared/src/main/java/org/readium/r2/shared/publication/Accessibility.kt
- readium/shared/src/test/java/org/readium/r2/shared/publication/AccessibilityTest.kt
- readium/streamer/src/main/java/org/readium/r2/streamer/parser/epub/AccessibilityAdapter.kt
- readium/streamer/src/test/java/org/readium/r2/streamer/parser/epub/MetadataTest.kt
- readium/streamer/src/test/resources/org/readium/r2/streamer/parser/epub/package/accessibility-epub2.opf
- readium/streamer/src/test/resources/org/readium/r2/streamer/parser/epub/package/accessibility-epub3.opf
* Support for [accessibility exemption metadata](https://readium.org/webpub-manifest/contexts/default/#exemption), which allows content creators to identify publications that do not meet conformance requirements but fall under exemptions in a given juridiction.
* Support for [EPUB Accessibility 1.1](https://www.w3.org/TR/epub-a11y-11/) conformance profiles.
* [go-toolkit#92](https://github.com/readium/go-toolkit/issues/92) The accessibility feature `printPageNumbers` is deprecated in favor of `pageNavigation`.
> Various accessibility metadata changes

- CHANGELOG.md
- readium/shared/src/main/java/org/readium/r2/shared/publication/Metadata.kt
- readium/shared/src/main/java/org/readium/r2/shared/publication/Tdm.kt
- readium/shared/src/test/java/org/readium/r2/shared/publication/MetadataTest.kt
- readium/shared/src/test/java/org/readium/r2/shared/publication/TdmTest.kt
- readium/streamer/src/main/java/org/readium/r2/streamer/parser/epub/Constants.kt
- readium/streamer/src/main/java/org/readium/r2/streamer/parser/epub/MetadataAdapter.kt
- readium/streamer/src/main/java/org/readium/r2/streamer/parser/epub/PropertyDataType.kt
- readium/streamer/src/test/java/org/readium/r2/streamer/parser/epub/MetadataTest.kt
- readium/streamer/src/test/resources/org/readium/r2/streamer/parser/epub/package/tdm-epub2.opf
- readium/streamer/src/test/resources/org/readium/r2/streamer/parser/epub/package/tdm-epub3.opf
* Support for [W3C's Text & data mining Reservation Protocol](https://www.w3.org/community/reports/tdmrep/CG-FINAL-tdmrep-20240510/) in our metadata models.
> Add support for TDM Reservation Protocol metadata

- CHANGELOG.md
- readium/navigator/src/main/java/org/readium/r2/navigator/epub/HtmlInjector.kt
- readium/streamer/src/main/java/org/readium/r2/streamer/parser/readium/ReadiumWebPubParser.kt
Fixes #641
Unlike swift-toolkit, this one did not set the correct `positionsServiceFactory` for WebPubs which conform to EPUB (regular EPUBs packaged as WebPub).
See https://github.com/readium/swift-toolkit/blob/develop/Sources/Streamer/Parser/Readium/ReadiumWebPubParser.swift#L108-L109
There also seemed to be an issue with FXL being the default layout, if none set via metadata.presentation. This does not seem to be the case with other toolkits and broke CSS/JS injections for our WebPubs. @mickael-menu maybe there is a smarter way to fix this?
> fix: webpub EPUBs

- .github/ISSUE_TEMPLATE/bug_report.yml
Update the bug report issue template to automatically set the `Bug` type instead of a `bug` label.
> Update the issue template

- readium/streamer/src/main/java/org/readium/r2/streamer/parser/epub/ResourceAdapter.kt
The incorrect rendition property 'spread-node' has been fixed to the correct 'spread-none' to ensure proper parsing of EPUB rendition metadata.
> fix: corrected typo 'spread-node' to 'spread-none'
